clarify how multiple layers of .attrs work
styled-components/styled-components-website pull request #720
Opened 2020-08-31 13:13 UTC by vzaidman

clarify how multiple layers of .attrs work to prevent confusions like in this issue: https://github.com/styled-components/styled-components/issues/3178

2020-10-02 20:25 UTC, probablyup requested changes

2020-10-02 20:25 UTC, probablyup commented on sections/basics/attaching-additional-props.md
> +Notice that when wrapping styled components, `.attrs` are applied from the innermost styled component to the uppermost styled component.
```suggestion
Notice that when wrapping styled components, `.attrs` are applied from the innermost styled component to the outermost styled component.
```

2020-10-02 20:25 UTC, probablyup commented on sections/basics/attaching-additional-props.md
> +This allows each level to **override** lower levels of `.attrs`, similarly to how css properties override css properties of inner components.
```suggestion
This allows each wrapper to **override** nested uses of `.attrs`, similarly to how css properties defined later in a stylesheet override previous declarations.
```

2020-10-02 20:25 UTC, probablyup commented on sections/basics/attaching-additional-props.md
> +Here `Input`'s `.attrs` are applied first, and then `PasswordInput`'s `.attrs`:
```suggestion
`Input`'s `.attrs` are applied first, and then `PasswordInput`'s `.attrs`:
```

2020-10-03 06:28 UTC, vzaidman commented
took all suggestions. thanks!

2020-10-05 01:22 UTC, probablyup approved these changes
Thank you for the improvement!

2020-10-05 01:22 UTC, merged